[layout]
preset = 1

[navigation]
tab_order = "columns_first"

[wm]
provider = "sway"

[theme]
background = "inherit"
border = "white"
border_selected = "cyan"
text = "white"
accent = "cyan"
selected = "blue"
warning = "yellow"
urgent = "red"

[navigation.keys]
left = "Left"
right = "Right"
up = "Up"
down = "Down"
tab = "Tab"
confirm = "Enter"
quit = "q"
