[[box]]
name = "sidebar"
x = 0.0
y = 0.0
w = 0.26
h = 0.55

[[box]]
name = "connectivity"
x = 0.0
y = 0.55
w = 0.26
h = 0.23

[[box]]
name = "power_menu"
x = 0.0
y = 0.78
w = 0.26
h = 0.22

[[box]]
name = "launcher"
x = 0.26
y = 0.0
w = 0.74
h = 0.09

[[box]]
name = "preview"
x = 0.26
y = 0.09
w = 0.74
h = 0.91
